### PR TITLE
Merge these somehow

### PR DESCRIPTION
**Pull request by abigailfails**

### CODE REVIEW

**Comment by bageldotjpg** [comment]
what are you trying to do

**Comment by abigailfails** [comment]
Merge them, but there are conflicts to resolve

**Comment by abigailfails** [comment]
wait sorry, not merge, i mean update the changes from master to enclosure

**Comment by bageldotjpg** [comment]
Merge what? enclosure into master? Is it finished?

**Comment by bageldotjpg** [comment]
Oh then you did this completely wrong, this PR is trying to merge enclouse into master

**Comment by abigailfails** [comment]
oh shit

**Pull request closed without merging**
